# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verademo-Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean verify
      
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip pipeline-scan.jar
 
    - name: Engage Ludicrous Speed - Run Pipeline Scan
      run: java -jar pipeline-scan.jar -f /home/runner/work/verademo-1/verademo-1/target/verademo.war -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_SECRET}}" --fail_on_severity="Very High, High" --issue_details true -jo true

    - name: Convert pipeline scan output to SARIF format
    id: convert
    uses: Veracode/veracode-pipeline-scan-results-to-sarif@v0.1.2
    with:
    pipeline-results-json: results.json
    output-results-sarif: veracode-results.sarif
    finding-rule-level: "3:1:0"

    - name: upload sarif file to repository
      uses: github/codeql-action/upload-sarif@v1
      with: # Path to SARIF file relative to the root of the repository
      sarif_file: veracode-results.sarif
